# Generated by Django 4.1.11 on 2024-11-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
