# Generated by Django 4.1.11 on 2024-11-18 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_alter_paymenthistory_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_payment', to=settings.AUTH_USER_MODEL),
        ),
    ]
