# Generated by Django 4.1.11 on 2024-04-05 10:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='duck.png', null=True, upload_to=api.models.user_directory_path),
        ),
    ]
