# Generated by Django 5.0.3 on 2024-04-06 17:58

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('location', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=500)),
                ('weather', models.CharField(max_length=500)),
                ('accomodation', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TourAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('image', models.ImageField(default='duck.png', upload_to=api.models.agent_directory_path)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.image_directory_path)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.destination')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='agent',
            field=models.ManyToManyField(related_name='agent_destination', to='api.touragent'),
        ),
        migrations.CreateModel(
            name='TourAgentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.agent_directory_path)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.touragent')),
            ],
        ),
    ]
