# Generated by Django 4.1.11 on 2024-04-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_destination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('culture', 'Culture'), ('food', 'Food'), ('wildlife', 'Wildlife'), ('nature', 'Nature')], default='All', max_length=15),
        ),
    ]
