# Generated by Django 4.1.11 on 2024-04-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
