# Generated by Django 5.0.3 on 2024-04-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touragent',
            name='image',
        ),
    ]
