# Generated by Django 5.0.3 on 2024-04-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_touragent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image',
        ),
    ]
