# Generated by Django 5.0.3 on 2024-05-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='for_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
