# Generated by Django 4.1.11 on 2024-10-27 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0001_initial'),
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('guest_number', models.IntegerField()),
                ('special_need', models.TextField(blank=True, null=True)),
                ('for_date', models.DateField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_agent', to='agent.agent')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_destination', to='destination.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
