# Generated by Django 4.1.11 on 2024-11-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['start_date']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='country',
            new_name='nationality',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='special_need',
            new_name='special_request',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='for_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='activities',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
