# Generated by Django 4.1.11 on 2024-11-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='phone',
            new_name='phone_no',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='activities',
        ),
    ]
