# Generated by Django 4.1.11 on 2024-10-27 18:49

import destination.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('location', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=500)),
                ('weather', models.CharField(max_length=500)),
                ('accomodation', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('culture', 'Culture'), ('food', 'Food'), ('wildlife', 'Wildlife'), ('nature', 'Nature'), ('adventure', 'Adventure')], default='All', max_length=15)),
                ('agent', models.ManyToManyField(related_name='agent_destination', to='agent.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_price', to='destination.destination')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=destination.models.destination_directory_path)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destination.destination')),
            ],
        ),
    ]
