# Generated by Django 4.1.11 on 2024-11-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_destinationcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='category',
        ),
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.ManyToManyField(related_name='destination_category', to='destination.destinationcategory'),
        ),
    ]
